### ISSUE TITLE
这么屌炸天的插件，为啥不提交到wordpress的插件库里面呢？

### ISSUE THREAD

**Issue by OItisTang** [ineo6/wp_video#6]
首先非常感谢您的插件！
超级好使，而且是HTML5的，这样我网站的视频在iOS上面也可以播放了！！！

话说这么好的插件，为啥不提交到wordpress的插件库呢？

这样能让更多的朋友使用，从而让更多的朋友从中获益！

--
汤承刚

**Comment by OItisTang** [comment]
PS: 我之所以说它屌炸天，是因为我首先尝试了wordpress上面的另一款针对国内一些视频网站的插件，不工作。。。
但是您这个插件非常有效，再次感谢！

**Comment by ineo6** [comment]
主要是申请麻烦，可能会不过过。另外感谢支持啊，很惭愧啊，维护的时间少。

**Comment by OItisTang** [comment]
无论如何，还是非常感谢！
只是希望更多人能像我一样受益：）
